---
homebrew_common_taps:
  - buo/cask-upgrade

homebrew_common_packages_present:
  - azure-cli
  - bash
  - black
  - coreutils
  - curl
  - exiftool
  - ffmpeg
  - gemini-cli
  - go
  - gpsbabel
  - graphviz
  - htop
  - imagemagick
  - jq
  - lazygit
  - maven
  - nvm
  - ollama
  - pipx
  - rsync
  - shellcheck
  - tfenv
  - tflint
  - tree
  - wget
  - yamllint
  - yarn

homebrew_common_packages_absent:
  - allure
  - ansible-lint  # remove first before removing ansible
  - ansible
  - checkov
  - composer
  - dialog
  - gobject-introspection
  - nghttp2
  - tldr

homebrew_common_cask_packages_present:
  - 1password
  - alfred
  - brave-browser
  - calibrite-profiler
  - chatgpt
  - cyberduck
  - firefox
  - font-hack-nerd-font
  - font-meslo-lg-nerd-font
  - gcloud-cli
  - google-chrome
  - google-drive
  - grandperspective
  - iTerm2
  - intellij-idea
  - logi-options-plus
  - postman
  - rancher
  - readdle-spark
  - rectangle
  - spotify
  - sublime-text
  - visual-studio-code

homebrew_common_cask_packages_absent:
  - anaconda
  - chronosync
  - cleanmymac
  - docker
  - google-backup-and-sync
  - i1profiler
  - mamp
  - nomachine
  - raindropio
  - scroll-reverser
  - skitch
  - textmate
  - zed
